// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgydjxzdcpemfshhvptw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpneWRqeHpkY3BlbWZzaGh2cHR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwOTkwOTQsImV4cCI6MjA3MTY3NTA5NH0.jgZyMP4b-VSOAjXbHkYmoU9o7WPHF0gP0s1TrBfUVB8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});